# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "agent-base-4.3.0" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-4.3.0.tgz";
        sha512 = "salcGninV0nPrwpGNn4VTXBb1SOuXQBiqbrNXoeizJsHrsL6ERFM2Ne3JUSBWRE6aeNJI2ROP/WEEIDUiDe3cg==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==";
      };
    };
    "es6-promise-4.2.8" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-4.2.8.tgz";
        sha512 = "HJDGx5daxeIvxdBxvG2cb9g4tEvwIk3i8+nhX0yGrYmZUzbkdg8QbDevheDB8gd0//uPj4c1EQua8Q+MViT0/w==";
      };
    };
    "es6-promisify-5.0.0" = {
      name = "es6-promisify";
      packageName = "es6-promisify";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promisify/-/es6-promisify-5.0.0.tgz";
        sha1 = "5109d62f3e56ea967c4b63505aef08291c8a5203";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "http-proxy-agent-2.1.0" = {
      name = "http-proxy-agent";
      packageName = "http-proxy-agent";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-proxy-agent/-/http-proxy-agent-2.1.0.tgz";
        sha512 = "qwHbBLV7WviBl0rQsOzH6o5lwyOIvwp/BdFnvVxXORldu5TmjFfjzBcWUWS5kWAZhmv+JtiDhSuQCp4sBfbIgg==";
      };
    };
    "https-proxy-agent-2.2.2" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-2.2.2.tgz";
        sha512 = "c8Ndjc9Bkpfx/vCJueCPy0jlP4ccCCSNDp8xwCZzPjKJUm+B+u9WX2x98Qx4n1PiMNTWo3D7KK5ifNV/yJyRzg==";
      };
    };
    "js-yaml-3.13.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.13.1.tgz";
        sha512 = "YfbcO7jXDdyj0DGxYVSlSeQNHbD7XPWvrVWeVUujrQEoZzWJIRrCPoyk6kL6IAjAG2IolMK4T0hNUe0HOUs5Jw==";
      };
    };
    "jsonc-parser-1.0.3" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-1.0.3.tgz";
        sha512 = "hk/69oAeaIzchq/v3lS50PXuzn5O2ynldopMC+SWBql7J2WtdptfB9dy8Y7+Og5rPkTCpn83zTiO8FMcqlXJ/g==";
      };
    };
    "jsonc-parser-2.1.0" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.1.0.tgz";
        sha512 = "n9GrT8rrr2fhvBbANa1g+xFmgGK5X91KFeDwlKQ3+SJfmH5+tKv/M/kahx/TXOMflfWHKGKqKyfHQaLKTNzJ6w==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "prettier-1.18.2" = {
      name = "prettier";
      packageName = "prettier";
      version = "1.18.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-1.18.2.tgz";
        sha512 = "OeHeMc0JhFE9idD4ZdtNibzY0+TPHSpSSb9h8FqtP+YnoZZ1sl8Vc9b1sasjfymH3SonAF4QcA2+mzHPhMvIiw==";
      };
    };
    "request-light-0.2.4" = {
      name = "request-light";
      packageName = "request-light";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-light/-/request-light-0.2.4.tgz";
        sha512 = "pM9Fq5jRnSb+82V7M97rp8FE9/YNeP2L9eckB4Szd7lyeclSIx02aIpPO/6e4m6Dy31+FBN/zkFMTd2HkNO3ow==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "vscode-json-languageservice-3.0.12" = {
      name = "vscode-json-languageservice";
      packageName = "vscode-json-languageservice";
      version = "3.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-json-languageservice/-/vscode-json-languageservice-3.0.12.tgz";
        sha512 = "XSgRVY/vsPqOa//ZwLD5DWx1wzTQGgeZfsOlVqFlLya10dpimSnd27kbuL45hzxh4B+MvmHZtZeWQKjSYnNF0A==";
      };
    };
    "vscode-jsonrpc-4.0.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-4.0.0.tgz";
        sha512 = "perEnXQdQOJMTDFNv+UF3h1Y0z4iSiaN9jIlb0OqIYgosPCZGYh/MCUlkFtV2668PL69lRDO32hmvL2yiidUYg==";
      };
    };
    "vscode-languageserver-4.4.2" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-4.4.2.tgz";
        sha512 = "61y8Raevi9EigDgg9NelvT9cUAohiEbUl1LOwQQgOCAaNX62yKny/ddi0uC+FUTm4CzsjhBu+06R+vYgfCYReA==";
      };
    };
    "vscode-languageserver-protocol-3.14.1" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.14.1.tgz";
        sha512 = "IL66BLb2g20uIKog5Y2dQ0IiigW0XKrvmWiOvc0yXw80z3tMEzEnHjaGAb3ENuU7MnQqgnYJ1Cl2l9RvNgDi4g==";
      };
    };
    "vscode-languageserver-types-3.14.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.14.0.tgz";
        sha512 = "lTmS6AlAlMHOvPQemVwo3CezxBp0sNB95KNPkqp3Nxd5VFEnuG1ByM0zlRWos0zjO3ZWtkvhal0COgiV1xIA4A==";
      };
    };
    "vscode-nls-3.2.5" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "3.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-3.2.5.tgz";
        sha512 = "ITtoh3V4AkWXMmp3TB97vsMaHRgHhsSFPsUdzlueSL+dRZbSNTZeOmdQv60kjCV306ghPxhDeoNUEm3+EZMuyw==";
      };
    };
    "vscode-nls-4.1.1" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-4.1.1.tgz";
        sha512 = "4R+2UoUUU/LdnMnFjePxfLqNhBS8lrAFyX7pjb2ud/lqDkrUavFUTcG7wR0HBZFakae0Q6KLBFjMS6W93F403A==";
      };
    };
    "vscode-uri-1.0.8" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-1.0.8.tgz";
        sha512 = "obtSWTlbJ+a+TFRYGaUumtVwb+InIUVI0Lu0VBUAPmj2cU5JutEXg3xUE0c2J5Tcy7h2DEKVJBFi+Y9ZSFzzPQ==";
      };
    };
    "yaml-ast-parser-custom-tags-0.0.43" = {
      name = "yaml-ast-parser-custom-tags";
      packageName = "yaml-ast-parser-custom-tags";
      version = "0.0.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml-ast-parser-custom-tags/-/yaml-ast-parser-custom-tags-0.0.43.tgz";
        sha512 = "R5063FF/JSAN6qXCmylwjt9PcDH6M0ExEme/nJBzLspc6FJDmHHIqM7xh2WfEmsTJqClF79A9VkXjkAqmZw9SQ==";
      };
    };
    "yaml-language-server-0.4.1" = {
      name = "yaml-language-server";
      packageName = "yaml-language-server";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml-language-server/-/yaml-language-server-0.4.1.tgz";
        sha512 = "KBGu6CvInpp2sZbAWiEqd0No7DKx8VKCvihKCcBQPIFM+eC8t02CnscsEaoMQMdvi5ceqcVzKkTgJdWPo6qi3Q==";
      };
    };
  };
in
{
  coc-python = nodeEnv.buildNodePackage {
    name = "coc-python";
    packageName = "coc-python";
    version = "1.2.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-python/-/coc-python-1.2.2.tgz";
      sha512 = "ULrSZnN/FLQEw5hIxbpCfIbwKkVKedqL9PZbub/ss/xP6HikABLB/U6Mn3EXwZTqHs823bgYwzw/ZDninh+Hrg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Python extension for coc.nvim, forked from vscode-python.";
      homepage = "https://github.com/neoclide/coc-python#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  coc-vimtex = nodeEnv.buildNodePackage {
    name = "coc-vimtex";
    packageName = "coc-vimtex";
    version = "1.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-vimtex/-/coc-vimtex-1.0.2.tgz";
      sha512 = "C1wz2WSEFEfKWdqxrGVup4hDcinswVuPY+3a47tZZ3RYO8cepRs8wzc2rDX9FYITMckAEWWS581WsRS54jTCWw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "vimtex integration for coc.nvim";
      homepage = "https://github.com/neoclide/coc-vimtex#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  coc-rls = nodeEnv.buildNodePackage {
    name = "coc-rls";
    packageName = "coc-rls";
    version = "1.1.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-rls/-/coc-rls-1.1.2.tgz";
      sha512 = "+srC3IcThFUvKChqnx/JwAUs0OJMrjjPXtjgLmrlUOZF211LHq8oYxxQQaf7mDAMDyDEyMgWQ615mJZP7s/3EQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Rust language support - code completion, Intellisense, refactoring, reformatting, errors, snippets. A client for the Rust Language Server, built by the RLS team.";
      homepage = "https://github.com/neoclide/coc-rls#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  coc-json = nodeEnv.buildNodePackage {
    name = "coc-json";
    packageName = "coc-json";
    version = "1.2.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-json/-/coc-json-1.2.3.tgz";
      sha512 = "JlM2CqVuDcxHAxVRcCTd2PsEzAU6jCwJ3N8jaszD3m2HSjq5I796Y7zFmoW6TK/7IOqAiYWCq1l+1yqjTSBedQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Json extension for coc.nvim";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  coc-yaml = nodeEnv.buildNodePackage {
    name = "coc-yaml";
    packageName = "coc-yaml";
    version = "1.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-yaml/-/coc-yaml-1.0.2.tgz";
      sha512 = "9EHs/bsv16sCAAJK4I6SMOcIwMZYYgw5SGhVhI+pMqcxbl40mZdWmEQSqNxTY4yYScBy+JWYRMm6cKmctbgrZw==";
    };
    dependencies = [
      sources."agent-base-4.3.0"
      sources."argparse-1.0.10"
      sources."debug-3.1.0"
      sources."es6-promise-4.2.8"
      sources."es6-promisify-5.0.0"
      sources."esprima-4.0.1"
      sources."http-proxy-agent-2.1.0"
      sources."https-proxy-agent-2.2.2"
      sources."js-yaml-3.13.1"
      sources."jsonc-parser-1.0.3"
      sources."ms-2.0.0"
      sources."prettier-1.18.2"
      (sources."request-light-0.2.4" // {
        dependencies = [
          sources."vscode-nls-4.1.1"
        ];
      })
      sources."sprintf-js-1.0.3"
      (sources."vscode-json-languageservice-3.0.12" // {
        dependencies = [
          sources."jsonc-parser-2.1.0"
        ];
      })
      sources."vscode-jsonrpc-4.0.0"
      sources."vscode-languageserver-4.4.2"
      sources."vscode-languageserver-protocol-3.14.1"
      sources."vscode-languageserver-types-3.14.0"
      sources."vscode-nls-3.2.5"
      sources."vscode-uri-1.0.8"
      sources."yaml-ast-parser-custom-tags-0.0.43"
      sources."yaml-language-server-0.4.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "yaml extension for coc.nvim";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  coc-css = nodeEnv.buildNodePackage {
    name = "coc-css";
    packageName = "coc-css";
    version = "1.2.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-css/-/coc-css-1.2.2.tgz";
      sha512 = "JvZnKZZJZemS70o972OEjfnMGGO2sLpJA3iX1OT3CXmaymPb8CmufboyCVnzGMDMbFL/qHgfjbdw9kOg5ZtzzQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Css extension for coc";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
}