# Generated by carnix 0.9.8: carnix generate-nix --standalone
with import <nixpkgs> {};
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO;
  diesel = crates.crates.diesel."1.4.2" deps;
  diesel_cli = crates.crates.diesel_cli."1.4.0" deps;
  diesel_derives = crates.crates.diesel_derives."1.4.0" deps;
  diesel_migrations = crates.crates.diesel_migrations."1.4.0" deps;
  migrations_internals = crates.crates.migrations_internals."1.4.0" deps;
  migrations_macros = crates.crates.migrations_macros."1.4.0" deps;
  __all = [ (diesel {}) (diesel_cli {}) (diesel_derives {}) (diesel_migrations {}) (migrations_internals {}) (migrations_macros {}) ];
  deps.aho_corasick."0.5.3" = {
    memchr = "0.1.11";
  };
  deps.aho_corasick."0.6.10" = {
    memchr = "2.2.0";
  };
  deps.ansi_term."0.11.0" = {
    winapi = "0.3.7";
  };
  deps.atty."0.2.11" = {
    termion = "1.5.3";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.autocfg."0.1.4" = {};
  deps.backtrace."0.3.31" = {
    backtrace_sys = "0.1.28";
    cfg_if = "0.1.9";
    libc = "0.2.58";
    rustc_demangle = "0.1.15";
    autocfg = "0.1.4";
  };
  deps.backtrace_sys."0.1.28" = {
    libc = "0.2.58";
    cc = "1.0.37";
  };
  deps.barrel."0.6.2" = {
    tempdir = "0.3.7";
  };
  deps.bigdecimal."0.1.0" = {
    num_bigint = "0.2.2";
    num_integer = "0.1.41";
    num_traits = "0.2.8";
  };
  deps.bitflags."1.1.0" = {};
  deps.byteorder."1.3.2" = {};
  deps.cc."1.0.37" = {};
  deps.cfg_if."0.1.9" = {};
  deps.chrono."0.4.7" = {
    libc = "0.2.58";
    num_integer = "0.1.41";
    num_traits = "0.2.8";
    time = "0.1.42";
  };
  deps.clap."2.33.0" = {
    atty = "0.2.11";
    bitflags = "1.1.0";
    strsim = "0.8.0";
    textwrap = "0.11.0";
    unicode_width = "0.1.5";
    vec_map = "0.8.1";
    ansi_term = "0.11.0";
  };
  deps.cloudabi."0.0.3" = {
    bitflags = "1.1.0";
  };
  deps.derive_error_chain."0.10.1" = {
    quote = "0.3.15";
    syn = "0.11.11";
  };
  deps.diesel."1.4.2" = {
    bigdecimal = "0.1.0";
    bitflags = "1.1.0";
    byteorder = "1.3.2";
    chrono = "0.4.7";
    diesel_derives = "1.4.0";
    ipnetwork = "0.13.1";
    libc = "0.2.58";
    libsqlite3_sys = "0.12.0";
    mysqlclient_sys = "0.2.4";
    num_bigint = "0.2.2";
    num_integer = "0.1.41";
    num_traits = "0.2.8";
    pq_sys = "0.4.6";
    quickcheck = "0.4.1";
    r2d2 = "0.8.5";
    serde_json = "1.0.39";
    time = "0.1.42";
    url = "1.7.2";
    uuid = "0.7.4";
  };
  deps.diesel_cli."1.4.0" = {
    barrel = "0.6.2";
    chrono = "0.4.7";
    clap = "2.33.0";
    diesel = "1.4.2";
    dotenv = "0.10.1";
    libsqlite3_sys = "0.12.0";
    migrations_internals = "1.4.0";
    serde = "1.0.93";
    tempfile = "3.0.8";
    toml = "0.4.10";
    url = "1.7.2";
  };
  deps.diesel_derives."1.4.0" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    syn = "0.15.38";
  };
  deps.diesel_migrations."1.4.0" = {
    migrations_internals = "1.4.0";
    migrations_macros = "1.4.0";
  };
  deps.difference."1.0.0" = {};
  deps.dotenv."0.10.1" = {
    derive_error_chain = "0.10.1";
    error_chain = "0.10.0";
    regex = "0.2.11";
  };
  deps.env_logger."0.3.5" = {
    log = "0.3.9";
    regex = "0.1.80";
  };
  deps.error_chain."0.10.0" = {
    backtrace = "0.3.31";
  };
  deps.fuchsia_cprng."0.1.1" = {};
  deps.heck."0.3.1" = {
    unicode_segmentation = "1.3.0";
  };
  deps.idna."0.1.5" = {
    matches = "0.1.8";
    unicode_bidi = "0.3.4";
    unicode_normalization = "0.1.8";
  };
  deps.ipnetwork."0.13.1" = {
    serde = "1.0.93";
    serde_derive = "1.0.93";
  };
  deps.itoa."0.4.4" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.lazy_static."1.3.0" = {};
  deps.libc."0.2.58" = {};
  deps.libsqlite3_sys."0.12.0" = {
    cc = "1.0.37";
    pkg_config = "0.3.14";
  };
  deps.lock_api."0.2.0" = {
    scopeguard = "1.0.0";
  };
  deps.log."0.3.9" = {
    log = "0.4.6";
  };
  deps.log."0.4.6" = {
    cfg_if = "0.1.9";
  };
  deps.matches."0.1.8" = {};
  deps.memchr."0.1.11" = {
    libc = "0.2.58";
  };
  deps.memchr."2.2.0" = {};
  deps.migrations_internals."1.4.0" = {
    barrel = "0.6.2";
    diesel = "1.4.2";
  };
  deps.migrations_macros."1.4.0" = {
    migrations_internals = "1.4.0";
    quote = "0.6.12";
    syn = "0.15.38";
  };
  deps.mysqlclient_sys."0.2.4" = {
    pkg_config = "0.3.14";
  };
  deps.num_bigint."0.2.2" = {
    num_integer = "0.1.41";
    num_traits = "0.2.8";
  };
  deps.num_integer."0.1.41" = {
    num_traits = "0.2.8";
    autocfg = "0.1.4";
  };
  deps.num_traits."0.2.8" = {
    autocfg = "0.1.4";
  };
  deps.numtoa."0.1.0" = {};
  deps.parking_lot."0.8.0" = {
    lock_api = "0.2.0";
    parking_lot_core = "0.5.0";
    rustc_version = "0.2.3";
  };
  deps.parking_lot_core."0.5.0" = {
    cfg_if = "0.1.9";
    rand = "0.6.5";
    smallvec = "0.6.10";
    rustc_version = "0.2.3";
    cloudabi = "0.0.3";
    redox_syscall = "0.1.54";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.percent_encoding."1.0.1" = {};
  deps.pkg_config."0.3.14" = {};
  deps.pq_sys."0.4.6" = {};
  deps.proc_macro2."0.4.30" = {
    unicode_xid = "0.1.0";
  };
  deps.quickcheck."0.4.1" = {
    env_logger = "0.3.5";
    log = "0.3.9";
    rand = "0.3.23";
  };
  deps.quote."0.3.15" = {};
  deps.quote."0.6.12" = {
    proc_macro2 = "0.4.30";
  };
  deps.r2d2."0.8.5" = {
    log = "0.4.6";
    parking_lot = "0.8.0";
    scheduled_thread_pool = "0.2.1";
  };
  deps.rand."0.3.23" = {
    libc = "0.2.58";
    rand = "0.4.6";
  };
  deps.rand."0.4.6" = {
    rand_core = "0.3.1";
    rdrand = "0.4.0";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.rand."0.6.5" = {
    rand_chacha = "0.1.1";
    rand_core = "0.4.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_jitter = "0.1.4";
    rand_os = "0.1.3";
    rand_pcg = "0.1.2";
    rand_xorshift = "0.1.1";
    autocfg = "0.1.4";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.rand_chacha."0.1.1" = {
    rand_core = "0.3.1";
    autocfg = "0.1.4";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.1";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rand_jitter."0.1.4" = {
    rand_core = "0.4.0";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.rand_os."0.1.3" = {
    rand_core = "0.4.0";
    rdrand = "0.4.0";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.rand_pcg."0.1.2" = {
    rand_core = "0.4.0";
    autocfg = "0.1.4";
  };
  deps.rand_xorshift."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.54" = {};
  deps.redox_termios."0.1.1" = {
    redox_syscall = "0.1.54";
  };
  deps.regex."0.1.80" = {
    aho_corasick = "0.5.3";
    memchr = "0.1.11";
    regex_syntax = "0.3.9";
    thread_local = "0.2.7";
    utf8_ranges = "0.1.3";
  };
  deps.regex."0.2.11" = {
    aho_corasick = "0.6.10";
    memchr = "2.2.0";
    regex_syntax = "0.5.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.3";
  };
  deps.regex_syntax."0.3.9" = {};
  deps.regex_syntax."0.5.6" = {
    ucd_util = "0.1.3";
  };
  deps.remove_dir_all."0.5.2" = {
    winapi = "0.3.7";
  };
  deps.rustc_demangle."0.1.15" = {};
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.ryu."0.2.8" = {};
  deps.scheduled_thread_pool."0.2.1" = {
    parking_lot = "0.8.0";
  };
  deps.scopeguard."1.0.0" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.93" = {
    serde_derive = "1.0.93";
  };
  deps.serde_derive."1.0.93" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    syn = "0.15.38";
  };
  deps.serde_json."1.0.39" = {
    itoa = "0.4.4";
    ryu = "0.2.8";
    serde = "1.0.93";
  };
  deps.smallvec."0.6.10" = {};
  deps.strsim."0.8.0" = {};
  deps.syn."0.11.11" = {
    quote = "0.3.15";
    synom = "0.11.3";
    unicode_xid = "0.0.4";
  };
  deps.syn."0.15.38" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    unicode_xid = "0.1.0";
  };
  deps.synom."0.11.3" = {
    unicode_xid = "0.0.4";
  };
  deps.tempdir."0.3.7" = {
    rand = "0.4.6";
    remove_dir_all = "0.5.2";
  };
  deps.tempfile."3.0.8" = {
    cfg_if = "0.1.9";
    rand = "0.6.5";
    remove_dir_all = "0.5.2";
    redox_syscall = "0.1.54";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.termion."1.5.3" = {
    numtoa = "0.1.0";
    libc = "0.2.58";
    redox_syscall = "0.1.54";
    redox_termios = "0.1.1";
  };
  deps.textwrap."0.11.0" = {
    unicode_width = "0.1.5";
  };
  deps.thread_id."2.0.0" = {
    kernel32_sys = "0.2.2";
    libc = "0.2.58";
  };
  deps.thread_local."0.2.7" = {
    thread_id = "2.0.0";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.time."0.1.42" = {
    libc = "0.2.58";
    redox_syscall = "0.1.54";
    winapi = "0.3.7";
  };
  deps.toml."0.4.10" = {
    serde = "1.0.93";
  };
  deps.ucd_util."0.1.3" = {};
  deps.unicode_bidi."0.3.4" = {
    matches = "0.1.8";
  };
  deps.unicode_normalization."0.1.8" = {
    smallvec = "0.6.10";
  };
  deps.unicode_segmentation."1.3.0" = {};
  deps.unicode_width."0.1.5" = {};
  deps.unicode_xid."0.0.4" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.url."1.7.2" = {
    idna = "0.1.5";
    matches = "0.1.8";
    percent_encoding = "1.0.1";
  };
  deps.utf8_ranges."0.1.3" = {};
  deps.utf8_ranges."1.0.3" = {};
  deps.uuid."0.6.5" = {
    cfg_if = "0.1.9";
  };
  deps.uuid."0.7.4" = {};
  deps.vcpkg."0.2.6" = {};
  deps.vec_map."0.8.1" = {};
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
}
