#pragma once

#define USE_SERIAL
#define SERIAL_USART_TX_PIN GP1

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define RP2040_FLASH_GD25Q64CS
#define FORCE_NKRO
#define USB_VBUS_PIN GP19
