#+TITLE: Split Keyboard

* Parts
- 2x Sweep36 (https://github.com/sadekbaroudi/sweep36)
  - reversible
  - hotswap
  - OLED support
  - Kailh Choc v1
- 2x Frood RP2040 Controller (Rev 9) (https://github.com/piit79/Frood)
  - Promicro layout
  - Elite-C extra PINs

  *WARNING*: This board utilizes the pin GP17 for an on-board LED,
  resulting in conflicts with the Sweep36 board. Sweep36 requires
  *ALL* pins. However, if you use the GP15 instead of the GP17, you
  can still use all keys. Otherwise, one key will not be usable. Now
  you can use the board like it does not have an on-board LED.

  /Alternatively/ (not done, only theorized) solder a wire from the
  non-working key to the pin GP6 (B1 label on the board). Make sure
  to solder on the right side (not the ground side). Then replace
  GP17 with GP6.

  The USB port is not perfectly centered, thus when flipping the board
  some USB cables might not fit into the port. The plastic of the USB
  cable interferes with the PCB. Try to solder the flipped PCB (right
  hand side) a little higher than the other.

- 36x Kailh Choc v1 Sunset Tactile Switches
- 36x Kailh Hotswap Sockets
- 36x Kailh Choc v1 Compatible Key Caps
- 1x TRRS Cable (30 cm)
- 2x TRRS Connector (through hole)
- 1x USB-C to USB-A Cable (2 m)
- 6x Rubber Feet (3mm height, 10mm diameter)

* Configuration Notice

The PCB is reversible, thus the pin's layout is the same for both
sides. Since both sides use the same layout, it is required to flip
the controller on one side.

** Elite-C Without LED on GP17
#+BEGIN_SRC json
{
	"matrix_pins": {
		"direct": [
			["GP9", "GP26", "GP27", "GP28", "GP29"],
			["GP8", "GP4", "GP5", "GP6", "GP7"],
			["GP20", "GP23", "GP21", "GP12", "GP13"],
			["GP17", "GP16", "GP14", null, null]
		]
	},
	"split": {
		"enabled": true
	}
}
#+END_SRC

** Elite-C With LED on GP17 (Frood)
#+BEGIN_SRC json
{
	"matrix_pins": {
		"direct": [
			["GP9", "GP26", "GP27", "GP28", "GP29"],
			["GP8", "GP4", "GP5", "GP6", "GP7"],
			["GP20", "GP23", "GP21", "GP12", "GP13"],
			["GP15", "GP16", "GP14", null, null]
		]
	},
	"split": {
		"enabled": true
	}
}
#+END_SRC

* Flash

#+BEGIN_SRC sh
sh qmk/flash.sh
#+END_SRC

* Stands

I use rubber spacers on the bottom of the PCB to prevent the keyboard
from sliding on my desk. These spacers should be at least 3 mm
tall. Put the spacers around the PCB to prevent the board from tilting
when pressing the bottom rows. There should be two spacers on the top,
two spacers on the bottom, and on spacers on the sides of the
controller.

** Thumb Pain
After using the keyboard for a while your inner part of your thumb
might start to hurt (right next to the nail). The pain is very
unpleasant but can be fixed. Increasing the height of the top side of
the board, by putting multiple spacers on-top of each other. I put
another 3 mm on the top side. Now the bottom side spacers are 3 mm
tall and the top side are 6 mm tall.

* Issues
** Pending

*** Keyboard Can Not Wake System
When the computer is sleeping, then it can not be woken up with this
keyboard. Other peripherals work.

** Fixed

*** Keyboard Not Responding After System Woken From Sleep
When putting the computer to sleep and wake it after wards, then the
keyboard is not responding. The keyboard needs to be re-plugged.

Fixed by adding the =#define USB_VBUS_PIN GP19= to =config.h=.

*** Keyboard Not Responding on System Boot
Currently the keyboard is not available when I start the computer. I
have to re-plug the keyboard to be able to use it.

Fixed by adding the =#define USB_VBUS_PIN GP19= to =config.h=.
