# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "copilot-node-server-1.14.0" = nodeEnv.buildNodePackage {
    name = "copilot-node-server";
    packageName = "copilot-node-server";
    version = "1.14.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/copilot-node-server/-/copilot-node-server-1.14.0.tgz";
      sha512 = "akyEGXwu/jZwc7+QIxkr/kKxiCp6yCQ9742J16/YposLMcgQHUDlag9WP+TjxD6HXPRFU53+8mKrUld5CS+slw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Copilot Node.js server stripped from https://github.com/github/copilot.vim";
      homepage = "https://github.com/jfcherng/copilot-node-server#readme";
      license = "GitHub Terms of Service";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
